
def check_new_revisions(branch, news_file: str | None) -> bool: ...

def increase_version(version: str, level: int = -1) -> str: ...

def expand_tag(template: str, version: str) -> str: ...

def unexpand_tag(template: str, tag: str) -> str: ...

def get_owned_crates(user: str) -> list[str]: ...

def cargo_publish(tree, subpath: str | None = None) -> None: ...

def find_version_in_cargo(tree) -> str: ...

def find_last_version_in_tags(branch, tag_name) -> tuple[str, str | None]: ...

def update_version_in_cargo(tree, version: str) -> None: ...

def update_version_in_manpage(tree, path, new_version: str, release_date) -> None: ...

def update_version_in_pyproject_toml(tree, new_version: str) -> None: ...
