
def check_new_revisions(branch, news_file: str | None) -> bool: ...

def increase_version(version: str, level: int = -1) -> str: ...

def expand_tag(template: str, version: str) -> str: ...

def get_owned_crates(user: str) -> list[str]: ...

def cargo_publish(tree, subpath: str | None = None) -> None: ...

def find_version_in_cargo(tree) -> str: ...

def update_version_in_cargo(tree, version: str) -> None: ...
